#167727300 setup unit testing
andela/nightcrawler-backend pull request #8
Opened 2019-08-19 14:54 UTC by orley12

#### What does this PR do?

- Setup unit testing

#### Description of Task to be completed?

- Setup unit testing

#### How should this be manually tested?

- Clone the repository, cd into the repository directory, and run npm install finally run npm test.

#### Any background context you want to provide?

- You might need to install node dependencies to test this chore 

#### What are the relevant pivotal tracker stories?

- [#167727300](https://www.pivotaltracker.com/story/show/167727300)

#### Questions:

- Please review pr

2019-08-20 10:54 UTC, Steelze commented on src/modules/user/tests/user.test.js
> +import chai, { should, expect, assert } from 'chai';
The sourceType key is present and set correctly to module in the eslintrc file. Do you have any idea why hound is reporting this?

2019-08-20 11:05 UTC, steelze reviewed
Hello Tosin, looking at your test command in the package.json and taking into account there will be several folders within the modules folder with its own tests subfolder. Running the test command should run all the tests in these different folders, or am I making a mistake?

2019-08-20 11:19 UTC, joaquinto requested changes
Good job @orley12 however you need to create room for mocha to pick up the test from any folder in the modules file. I think you should use something like `./src/modules/*/*.test.js` and see if it works. So that means that every of our test files will be named something like this `user.test.js`. 
Great job man.

2019-08-20 11:23 UTC, orley12 commented on src/modules/user/tests/user.test.js
> +import chai, { should, expect, assert } from 'chai';
I have no idea why, i have googled the error message and the solution is already present in the 
es-lint config file
"parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
    }

2019-08-20 11:24 UTC, Steelze commented
> Good job @orley12 however you need to create room for mocha to pick up the test from any folder in the modules file. I think you should use something like `./src/modules/*/*.test.js` and see if it works. So that means that every of our test files will be named something like this `user.test.js`.
> Great job man.

You can modify the command to run every file in the tests folder, I believe every module subfolder should have a tests folder within. This will help to reduce having a single bulky test file.

2019-08-20 11:24 UTC, shonubijerry reviewed
Good job @orley12. However, I believe the test setup should be something encompassing.
You can use `mocha ./src/test/**/*.js --recursive --require @babel/register` in the test script so that anyone creating test in the future will just dump their test in the ./src/test folder.

2019-08-20 11:24 UTC, shonubijerry commented on src/modules/user/tests/user.test.js
> +import chai, { should, expect, assert } from 'chai';
I think we should use just one of the assertions on line 2. Using all will not make our code consistent. My thoughts anyway.

2019-08-20 11:24 UTC, shonubijerry commented on package.json
> +    "test": "mocha src/modules/user/tests --recursive --require @babel/register",
Are we to put test files in each module or use the general test folder in /src/test

2019-08-20 11:27 UTC, joaquinto commented
> > Good job @orley12 however you need to create room for mocha to pick up the test from any folder in the modules file. I think you should use something like `./src/modules/*/*.test.js` and see if it works. So that means that every of our test files will be named something like this `user.test.js`.
> > Great job man.
> 
> You can modify the command to run every file in the tests folder, I believe every module subfolder should have a tests folder within. This will help to reduce having a single bulky test file.

Ok than. That means he will be targeting a folder structure like this `./src/modules/*/test` right?

2019-08-20 11:28 UTC, Steelze commented
> > > Good job @orley12 however you need to create room for mocha to pick up the test from any folder in the modules file. I think you should use something like `./src/modules/*/*.test.js` and see if it works. So that means that every of our test files will be named something like this `user.test.js`.
> > > Great job man.
> > 
> > 
> > You can modify the command to run every file in the tests folder, I believe every module subfolder should have a tests folder within. This will help to reduce having a single bulky test file.
> 
> Ok than. That means he will be targeting a folder structure like this `./src/modules/*/test` right?

Yeah

2019-08-20 11:31 UTC, Steelze commented on src/modules/user/tests/user.test.js
> +import chai, { should, expect, assert } from 'chai';
Noticed that too Tosin. I also agree with Korede, using one of the assertions will do just fine.

2019-08-20 11:32 UTC, Steelze commented
So Tosin you might end up with something like `mocha s./src/modules/*/tests --recursive --require @babel/register`

2019-08-20 11:40 UTC, joaquinto commented
> Good job @orley12. However, I believe the test setup should be something encompassing.
> You can use `mocha ./src/test/**/*.js --recursive --require @babel/register` in the test script so that anyone creating test in the future will just dump their test in the ./src/test folder.

@shonubijerry Our @jsamchineme said we should have our test in the module folder. So for each module we can have a test folder containing the tests for that module.

2019-08-20 12:13 UTC, orley12 commented on src/modules/user/tests/user.test.js
> +import chai, { should, expect, assert } from 'chai';
Should we hold a discussion on which one we should use because some people can use should, others expect , and some assert.

2019-08-20 12:15 UTC, orley12 commented
> Hello Tosin, looking at your test command in the package.json and taking into account there will be several folders within the modules folder with its own tests subfolder. Running the test command should run all the tests in these different folders, or am I making a mistake?



> Good job @orley12 however you need to create room for mocha to pick up the test from any folder in the modules file. I think you should use something like `./src/modules/*/*.test.js` and see if it works. So that means that every of our test files will be named something like this `user.test.js`.
> Great job man.

I have applied your suggestion, thank you for the feedback.

2019-08-20 12:22 UTC, orley12 commented
> Good job @orley12. However, I believe the test setup should be something encompassing.
> You can use `mocha ./src/test/**/*.js --recursive --require @babel/register` in the test script so that anyone creating test in the future will just dump their test in the ./src/test folder.

I used all assertion libraries with the consideration that not everybody might know how to use the assertion library of choice. Do you think we should hold a pool to choose one?

2019-08-20 12:23 UTC, orley12 commented
> > Good job @orley12 however you need to create room for mocha to pick up the test from any folder in the modules file. I think you should use something like `./src/modules/*/*.test.js` and see if it works. So that means that every of our test files will be named something like this `user.test.js`.
> > Great job man.
> 
> You can modify the command to run every file in the tests folder, I believe every module subfolder should have a tests folder within. This will help to reduce having a single bulky test file.

Thank you for your feedback, i have taken care of this.

2019-08-20 12:47 UTC, shonubijerry commented
> > Good job @orley12. However, I believe the test setup should be something encompassing.
> > You can use `mocha ./src/test/**/*.js --recursive --require @babel/register` in the test script so that anyone creating test in the future will just dump their test in the ./src/test folder.
> 
> @shonubijerry, @jsamchineme said we should have our test in the module folder. So for each module we can have a test folder containing the tests for that module.

@orley12 this is better based on our agreed folder structure
`mocha ./src/modules/**/*.test.js --recursive --require @babel/register`

2019-08-20 16:44 UTC, orley12 commented
> > > Good job @orley12. However, I believe the test setup should be something encompassing.
> > > You can use `mocha ./src/test/**/*.js --recursive --require @babel/register` in the test script so that anyone creating test in the future will just dump their test in the ./src/test folder.
> > 
> > 
> > @shonubijerry, @jsamchineme said we should have our test in the module folder. So for each module we can have a test folder containing the tests for that module.
> 
> @orley12 this is better based on our agreed folder structure
> `mocha ./src/modules/**/*.test.js --recursive --require @babel/register`
> Kindly implement it so that we can approve it.

I have implemented your feedback about using a single assertion, **assert** in this case  .

2019-08-20 16:56 UTC, shonubijerry submitted a review, later dismissed

2019-08-20 16:58 UTC, joaquinto submitted a review, later dismissed
This looks good. Good job man.

2019-08-20 18:31 UTC, jsamchineme approved these changes

2019-08-20 18:33 UTC, jsamchineme approved these changes

2019-08-20 19:07 UTC, joaquinto approved these changes

2019-08-21 04:38 UTC, steelze approved these changes

2019-08-21 07:30 UTC, merged